project_id = "fhdyflgojppwgrscmtdp"

[functions.generate-content]
verify_jwt = false

[functions.storytelling-ai]
verify_jwt = false

[functions.persona-ai]
verify_jwt = false

[functions.proposition-ai]
verify_jwt = false

[functions.niche-ai]
verify_jwt = false
