project_id = "fhdyflgojppwgrscmtdp"

[functions.generate-content]
verify_jwt = false

[functions.storytelling-ai]
verify_jwt = false

[functions.persona-ai]
verify_jwt = false

[functions.proposition-ai]
verify_jwt = false

[functions.niche-ai]
verify_jwt = false

[functions.strategy-ai]
verify_jwt = false

[functions.linkedin-ai]
verify_jwt = false

[functions.pinterest-ai]
verify_jwt = false

[functions.website-ai]
verify_jwt = false

[functions.inspire-ai]
verify_jwt = false

[functions.fetch-instagram-post]
verify_jwt = false

[functions.creative-flow]
verify_jwt = false

[functions.launch-plan-ai]
verify_jwt = false
